### ISSUE TITLE
could you add "Version Lens" in list?

### ISSUE THREAD

**Issue by seattlesbest** [ricardoemerson/flutter-development-extensions-pack#1]
I always appreciate the simplicity of devcontainer.json as it allows me to add numerous extension packs in one line thanks to recard-emerson.
Please add a version lens along with dependency search as it has been very useful with dart support.

https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens

**Comment by ricardoemerson** [comment]
This extension it is included in another extension pack that I created.

[Base Development Extensions Pack](https://marketplace.visualstudio.com/items?itemName=ricardo-emerson.base-development-extensions-pack)
